{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vapro.lsplant",
    "module": "lsplant-pro",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lsplant-pro-1.0.0.aar",
          "url": "lsplant-pro-1.0.0.aar",
          "size": 13359780,
          "sha512": "8bdd803fee14c36b5441c0e5ff779d487fa40234ea629f5173805b30c9bdc3d3b2b54acdfad5cc72598586b48c8eb8324dcabea4259ef17ed63c30d422448dd3",
          "sha256": "eb1b17ec85f719acb109bb3464a4b11aba92fde37132d92fe6e34ca20b322222",
          "sha1": "e50f9d46cfd3e46ce4edee5bcd987ef46e719762",
          "md5": "e5183b978fbaaf136bc573e928043ab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lsplant-pro-1.0.0.aar",
          "url": "lsplant-pro-1.0.0.aar",
          "size": 13359780,
          "sha512": "8bdd803fee14c36b5441c0e5ff779d487fa40234ea629f5173805b30c9bdc3d3b2b54acdfad5cc72598586b48c8eb8324dcabea4259ef17ed63c30d422448dd3",
          "sha256": "eb1b17ec85f719acb109bb3464a4b11aba92fde37132d92fe6e34ca20b322222",
          "sha1": "e50f9d46cfd3e46ce4edee5bcd987ef46e719762",
          "md5": "e5183b978fbaaf136bc573e928043ab8"
        }
      ]
    }
  ]
}
